# Copied from geopandas .travis.yml
language: python
python: 3.7

sudo: false

matrix:
  include:
    - env: ENV_FILE="envs/basmati_env.yml"

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info

  # Install dependencies
  - conda env create --file="${ENV_FILE}"
  - source activate basmati_env
  - pip install -e .
  - conda list
  - python -c "import basmati; print(basmati.__version__);"

script:
  - nosetests basmati

# 
# after_success:
#   - codecov
# 
